
[[pages]]
  lastUpdated = 2025-08-12T23:26:28+00:00
  route = "/echoes/angelfold"

  [[pages.changes]]
    at = 2025-03-04T17:05:30+00:00
    hash = "9938c0e"
    message = "Start working on angelfold february report"

  [[pages.changes]]
    at = 2025-03-21T08:33:48+00:00
    hash = "d790170"
    message = "Mark angelfold stuff as drafts"

  [[pages.changes]]
    at = 2025-06-11T05:18:48+00:00
    hash = "d2510af"
    message = "Update posts to fit the new generator changes"

  [[pages.changes]]
    at = 2025-08-12T23:26:28+00:00
    hash = "8dd4654"
    message = "Migrate content to new format"

[[pages]]
  lastUpdated = 2025-08-12T23:26:28+00:00
  route = "/echoes/the-realm-s-secrets"

  [[pages.changes]]
    at = 2024-10-31T17:43:13+00:00
    hash = "ec65faf"
    message = "Generate multiple pages & metadata collection"

  [[pages.changes]]
    at = 2024-11-06T03:26:30+00:00
    hash = "4ca0d22"
    message = "Code highlighting, and a major refactor of the rendering code"

  [[pages.changes]]
    at = 2024-11-06T07:34:21+00:00
    hash = "3206bd5"
    message = "Post list page"

  [[pages.changes]]
    at = 2025-03-03T21:34:06+00:00
    hash = "cda7f88"
    message = "Allow building without .git"

  [[pages.changes]]
    at = 2025-03-03T23:05:02+00:00
    hash = "9eb0935"
    message = "Add strikethrough support"

  [[pages.changes]]
    at = 2025-03-03T23:39:15+00:00
    hash = "ca5493f"
    message = "Fix lint errors"

  [[pages.changes]]
    at = 2025-03-20T16:41:19+00:00
    hash = "a385fbe"
    message = "I forgor what I changed"

  [[pages.changes]]
    at = 2025-06-11T05:18:48+00:00
    hash = "d2510af"
    message = "Update posts to fit the new generator changes"

  [[pages.changes]]
    at = 2025-08-12T23:26:28+00:00
    hash = "8dd4654"
    message = "Migrate content to new format"

[[pages]]
  lastUpdated = 2025-08-12T23:26:28+00:00
  route = "/echoes/ts-array-variance-standup"

  [[pages.changes]]
    at = 2025-06-18T20:59:11+00:00
    hash = "8a3b07b"
    message = "Add Standup variance explainer post"

  [[pages.changes]]
    at = 2025-06-18T21:07:36+00:00
    hash = "e77cc19"
    message = "Add correction to standup thingy"

  [[pages.changes]]
    at = 2025-06-19T11:36:45+00:00
    hash = "c97acef"
    message = "Tight -> narrow"

  [[pages.changes]]
    at = 2025-07-23T21:51:03+00:00
    hash = "324217e"
    message = "Add a few more people to the arc pookies bug finder list"

  [[pages.changes]]
    at = 2025-08-12T23:26:28+00:00
    hash = "8dd4654"
    message = "Migrate content to new format"

[[pages]]
  lastUpdated = 2025-08-12T23:26:28+00:00
  route = "/echoes/arcaea-pookies"

  [[pages.changes]]
    at = 2025-03-03T21:34:06+00:00
    hash = "cda7f88"
    message = "Allow building without .git"

  [[pages.changes]]
    at = 2025-03-04T00:03:18+00:00
    hash = "b0e12a6"
    message = "Add descriptions to more pages"

  [[pages.changes]]
    at = 2025-03-04T17:05:30+00:00
    hash = "9938c0e"
    message = "Start working on angelfold february report"

  [[pages.changes]]
    at = 2025-03-20T16:41:19+00:00
    hash = "a385fbe"
    message = "I forgor what I changed"

  [[pages.changes]]
    at = 2025-06-11T05:18:48+00:00
    hash = "d2510af"
    message = "Update posts to fit the new generator changes"

  [[pages.changes]]
    at = 2025-06-11T21:14:43+00:00
    hash = "49bac70"
    message = "Fix typos"

  [[pages.changes]]
    at = 2025-07-23T21:51:03+00:00
    hash = "324217e"
    message = "Add a few more people to the arc pookies bug finder list"

  [[pages.changes]]
    at = 2025-07-28T17:42:59+00:00
    hash = "90b7e89"
    message = "Update arc pookies links"

  [[pages.changes]]
    at = 2025-08-06T22:48:15+00:00
    hash = "00d81f7"
    message = "Bump patched app links"

  [[pages.changes]]
    at = 2025-08-12T23:26:28+00:00
    hash = "8dd4654"
    message = "Migrate content to new format"

[[pages]]
  lastUpdated = 2025-08-12T23:26:28+00:00
  route = ""

  [[pages.changes]]
    at = 2024-10-31T17:43:13+00:00
    hash = "ec65faf"
    message = "Generate multiple pages & metadata collection"

  [[pages.changes]]
    at = 2024-10-31T19:06:07+00:00
    hash = "72aa525"
    message = "More `aside` classes and whatnot"

  [[pages.changes]]
    at = 2024-11-06T03:26:30+00:00
    hash = "4ca0d22"
    message = "Code highlighting, and a major refactor of the rendering code"

  [[pages.changes]]
    at = 2025-03-03T21:34:06+00:00
    hash = "cda7f88"
    message = "Allow building without .git"

  [[pages.changes]]
    at = 2025-03-04T00:03:18+00:00
    hash = "b0e12a6"
    message = "Add descriptions to more pages"

  [[pages.changes]]
    at = 2025-06-11T05:18:48+00:00
    hash = "d2510af"
    message = "Update posts to fit the new generator changes"

  [[pages.changes]]
    at = 2025-08-12T23:26:28+00:00
    hash = "8dd4654"
    message = "Migrate content to new format"

[[pages]]
  lastUpdated = 2025-08-12T23:26:28+00:00
  route = "/echoes/games"

  [[pages.changes]]
    at = 2024-11-01T03:36:46+00:00
    hash = "363ea62"
    message = "Continue working on gaming post"

  [[pages.changes]]
    at = 2024-11-02T03:33:36+00:00
    hash = "632f35c"
    message = "Add an actual page structure and whatnot"

  [[pages.changes]]
    at = 2024-11-02T20:15:19+00:00
    hash = "f7559c0"
    message = "Change styling a bit"

  [[pages.changes]]
    at = 2024-11-06T03:26:30+00:00
    hash = "4ca0d22"
    message = "Code highlighting, and a major refactor of the rendering code"

  [[pages.changes]]
    at = 2024-11-07T07:50:05+00:00
    hash = "d604ca6"
    message = "404 page, sitemap, and some linters"

  [[pages.changes]]
    at = 2024-11-08T07:52:29+00:00
    hash = "c11326b"
    message = "Make TOCs a bit prettier"

  [[pages.changes]]
    at = 2024-12-01T17:25:55+00:00
    hash = "942c0fc"
    message = "Make tiny tweaks"

  [[pages.changes]]
    at = 2025-03-03T21:34:06+00:00
    hash = "cda7f88"
    message = "Allow building without .git"

  [[pages.changes]]
    at = 2025-03-04T17:05:30+00:00
    hash = "9938c0e"
    message = "Start working on angelfold february report"

  [[pages.changes]]
    at = 2025-06-11T05:18:48+00:00
    hash = "d2510af"
    message = "Update posts to fit the new generator changes"

  [[pages.changes]]
    at = 2025-08-12T23:26:28+00:00
    hash = "8dd4654"
    message = "Migrate content to new format"

[[pages]]
  lastUpdated = 2025-08-12T23:26:28+00:00
  route = "/echoes/angelfold-2025-february"

  [[pages.changes]]
    at = 2025-03-04T17:05:30+00:00
    hash = "9938c0e"
    message = "Start working on angelfold february report"

  [[pages.changes]]
    at = 2025-03-20T16:41:19+00:00
    hash = "a385fbe"
    message = "I forgor what I changed"

  [[pages.changes]]
    at = 2025-03-21T08:33:48+00:00
    hash = "d790170"
    message = "Mark angelfold stuff as drafts"

  [[pages.changes]]
    at = 2025-06-11T05:18:48+00:00
    hash = "d2510af"
    message = "Update posts to fit the new generator changes"

  [[pages.changes]]
    at = 2025-08-12T23:26:28+00:00
    hash = "8dd4654"
    message = "Migrate content to new format"

[[pages]]
  lastUpdated = 2025-08-12T23:26:28+00:00
  route = "/echoes/arcaea"

  [[pages.changes]]
    at = 2024-10-15T06:01:36+00:00
    hash = "9ffac14"
    message = "Inital setup"

  [[pages.changes]]
    at = 2024-10-31T15:30:32+00:00
    hash = "1076995"
    message = "Templating system"

  [[pages.changes]]
    at = 2024-10-31T17:43:13+00:00
    hash = "ec65faf"
    message = "Generate multiple pages & metadata collection"

  [[pages.changes]]
    at = 2024-10-31T19:06:07+00:00
    hash = "72aa525"
    message = "More `aside` classes and whatnot"

  [[pages.changes]]
    at = 2024-11-01T03:36:46+00:00
    hash = "363ea62"
    message = "Continue working on gaming post"

  [[pages.changes]]
    at = 2024-11-02T04:22:31+00:00
    hash = "4d1e3e0"
    message = "Properly handle creation/update dates"

  [[pages.changes]]
    at = 2024-11-02T20:15:19+00:00
    hash = "f7559c0"
    message = "Change styling a bit"

  [[pages.changes]]
    at = 2024-11-06T03:26:30+00:00
    hash = "4ca0d22"
    message = "Code highlighting, and a major refactor of the rendering code"

  [[pages.changes]]
    at = 2024-11-06T07:34:21+00:00
    hash = "3206bd5"
    message = "Post list page"

  [[pages.changes]]
    at = 2024-11-06T09:09:11+00:00
    hash = "bc3d9f7"
    message = "More work on the arcaea post"

  [[pages.changes]]
    at = 2024-11-07T07:50:05+00:00
    hash = "d604ca6"
    message = "404 page, sitemap, and some linters"

  [[pages.changes]]
    at = 2024-11-08T06:45:00+00:00
    hash = "17f49c2"
    message = "Implement base table of contents logic"

  [[pages.changes]]
    at = 2024-11-08T07:52:29+00:00
    hash = "c11326b"
    message = "Make TOCs a bit prettier"

  [[pages.changes]]
    at = 2025-03-03T21:34:06+00:00
    hash = "cda7f88"
    message = "Allow building without .git"

  [[pages.changes]]
    at = 2025-03-04T17:05:30+00:00
    hash = "9938c0e"
    message = "Start working on angelfold february report"

  [[pages.changes]]
    at = 2025-06-11T05:18:48+00:00
    hash = "d2510af"
    message = "Update posts to fit the new generator changes"

  [[pages.changes]]
    at = 2025-08-12T23:26:28+00:00
    hash = "8dd4654"
    message = "Migrate content to new format"

[[pages]]
  lastUpdated = 2025-08-12T23:26:28+00:00
  route = "/echoes"

  [[pages.changes]]
    at = 2024-11-06T03:26:30+00:00
    hash = "4ca0d22"
    message = "Code highlighting, and a major refactor of the rendering code"

  [[pages.changes]]
    at = 2024-11-06T07:34:21+00:00
    hash = "3206bd5"
    message = "Post list page"

  [[pages.changes]]
    at = 2024-11-06T09:09:11+00:00
    hash = "bc3d9f7"
    message = "More work on the arcaea post"

  [[pages.changes]]
    at = 2024-11-07T07:50:05+00:00
    hash = "d604ca6"
    message = "404 page, sitemap, and some linters"

  [[pages.changes]]
    at = 2025-03-04T00:03:18+00:00
    hash = "b0e12a6"
    message = "Add descriptions to more pages"

  [[pages.changes]]
    at = 2025-06-11T05:18:48+00:00
    hash = "d2510af"
    message = "Update posts to fit the new generator changes"

  [[pages.changes]]
    at = 2025-08-12T23:26:28+00:00
    hash = "8dd4654"
    message = "Migrate content to new format"

[[pages]]
  lastUpdated = 2025-08-12T23:26:28+00:00
  route = "/404"

  [[pages.changes]]
    at = 2024-11-07T07:50:05+00:00
    hash = "d604ca6"
    message = "404 page, sitemap, and some linters"

  [[pages.changes]]
    at = 2025-03-03T21:34:06+00:00
    hash = "cda7f88"
    message = "Allow building without .git"

  [[pages.changes]]
    at = 2025-06-19T12:01:50+00:00
    hash = "a8cba40"
    message = "Shorten 404 spam for mobile"

  [[pages.changes]]
    at = 2025-08-12T23:26:28+00:00
    hash = "8dd4654"
    message = "Migrate content to new format"

[[pages]]
  lastUpdated = 2025-08-12T23:26:28+00:00
  route = "/echoes/spherical-cmb"

  [[pages.changes]]
    at = 2025-03-20T17:07:08+00:00
    hash = "249e5f0"
    message = "Add iota puzzle and cmb page"

  [[pages.changes]]
    at = 2025-03-20T17:31:37+00:00
    hash = "c4df671"
    message = "Include html version of the iota manuscript"

  [[pages.changes]]
    at = 2025-03-20T17:37:12+00:00
    hash = "e532206"
    message = "Remove html version of the iota puzzle"

  [[pages.changes]]
    at = 2025-03-20T17:39:26+00:00
    hash = "029aaac"
    message = "Tiny change in iota puzzle"

  [[pages.changes]]
    at = 2025-03-21T12:54:15+00:00
    hash = "d12baca"
    message = "Hide links to paper on riddle page"

  [[pages.changes]]
    at = 2025-03-25T21:42:26+00:00
    hash = "2326f47"
    message = "Implement Silo's suggestion"

  [[pages.changes]]
    at = 2025-06-11T05:18:48+00:00
    hash = "d2510af"
    message = "Update posts to fit the new generator changes"

  [[pages.changes]]
    at = 2025-08-12T23:26:28+00:00
    hash = "8dd4654"
    message = "Migrate content to new format"

[[pages]]
  lastUpdated = 2025-08-12T23:26:28+00:00
  route = "/echoes/updating-lunarbox"

  [[pages.changes]]
    at = 2025-06-11T05:18:54+00:00
    hash = "7f55203"
    message = "Start working on lunarbox article"

  [[pages.changes]]
    at = 2025-08-12T23:26:28+00:00
    hash = "8dd4654"
    message = "Migrate content to new format"
