[private]
@default:
  just --list

[group("build")]
[doc("Build an odin package with the required configuration set")]
@build source *args:
  odin build {{ source }} \
    -linker:mold \
    -show-timings \
    {{ args }}

[group("build")]
[group("debug")]
[doc("Build `anima` in debug mode")]
@build-debug:
  mkdir -p build/debug
  just build src \
    -debug \
    -out:build/debug/anima.bin

[group("debug")]
[doc("Run `anima` in debug mode")]
@run-debug: build-debug
  ./build/debug/anima.bin

[group("debug")]
[doc("Run `anima` inside `valgrind`")]
@grind: build-debug
  valgrind --leak-check=full ./build/debug/anima.bin

[group("debug")]
[doc("Type-check the `anima` codebase")]
@check:
  odin check src -show-timings

[group("debug")]
[doc("Run a live debug server")]
@watch-debug:
  #!/usr/bin/env -S parallel --shebang --halt-on-error 2 --line-buffer
  live-server dist --port 8080 --poll
  watchexec --quiet --restart --watch src just run-debug
  watchexec --quiet --restart --postpone --watch example ./build/debug/anima.bin
